### ISSUE TITLE
Userdefined variables can easily mess up generated standalone device code

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2#1302]
Hi there,

Any of the `NeuronGroup` examples below messes up the generated C++ Standalone code.

```python
from brian2 import *

set_device('cpp_standalone')

lam = 0.5
G = NeuronGroup(5, 'x : integer')
G.run_regularly('''x = poisson(lam)''')

G1 = NeuronGroup(5, 'x : integer', namespace={'lam': 0.1})
G1.run_regularly('''x = poisson(lam)''')

G2 = NeuronGroup(5, 'x : integer', namespace={'a': 0.1})
G2.run_regularly('''x = poisson(a)''')

G3 = NeuronGroup(5, 'x : integer', namespace={'_poisson': 0.1})
G3.run_regularly('''x = poisson(_poisson)''')

run(defaultclock.dt)

```
They produce errors like this:
```
|| code_objects/neurongroup_1_run_regularly_codeobject.cpp:49:31: error: expected ‘,’ or ‘...’ before numeric constant
||    49 |  int32_t _poisson_mult(double 0.1, int _vectorisation_idx) {
||       |                               ^~~
```
Here, the argument `double lam` of the `_poisson_mult` function was replaces by `double 0.1` in the function definition.

Reason is that the C++ Standalone implementation of the `poisson` function uses variables with names `lam`, `a` and `_poisson`. When these variables are used in the namespace, they seem to be simply replaces by their scalar values, even if `_poisson` is actually a function and `lam` and `a` function arguments.

Suggestion:
- Don't allow user-defined variables to start with underscore. Or at least ignore those in the `Group.resolve_all(...)` calls.
- Make sure all functions and variables that are not user-defined are actually prefixed with underscore. This is already happening in many places but not consistently. E.g. the `poisson` implementation uses variables `a`, `lam` and others that could typically be used as variables by users.

**Comment by mstimberg** [comment]
Hi @denisalevi, thanks for the thorough report. I'll look into this in more detail tomorrow, but I think at least some of these examples should be fixed already, see #1276.

**Comment by denisalevi** [comment]
Ah yeah, shoot. I pulled current master but ran in the wrong environment (with an old brian2 version) 🤦‍♂️

Alright, the first three examples work fine on current master. But the last example (`G3`) still fails because a `const double _poisson = 0.1` is generated, which overwrite the function definition of `_poisson`.

In general, is there anything I need to watch out for in variable/function naming in standalone code? I mean any variable I use in a codeobject run  function could in principle be a user-defined variable. Should all standalone code variables start with underscore (DEFAULT_FUNCTIONS do mostly, but my general code does not always do that and I was already wondering at times if this can break things).

And one thing persists, even if everything was underscored, there is nothing stopping users from naming their variables with underscore as well. Any thought on that?

**Comment by thesamovar** [comment]
I suppose really we ought to use unmistakable prefixes for user variables rather than the other way round?

**Comment by mstimberg** [comment]
> I suppose really we ought to use unmistakable prefixes for user variables rather than the other way round?

Hmm, not sure if I agree. We already prefix everything in the templates and the default function names with underscores to avoid them clashing with user-defined names, and we do not allow names starting with underscores for user variables in equations, etc. If I am not mistaken, the only thing needed to fix the issue reported by @denisalevi is to also explicitly forbid underscore-prefixed names for external constants/namespace keys. I don't think many users were relying on this to work in the first place, and the fix should be straightforward.
Changing all the user variable names would mean that error messages about the generated code would be further away from what the user wrote, which is something we generally try to avoid.

**Comment by thesamovar** [comment]
Fair points!
